# Generated by Django 4.0 on 2021-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(choices=[('Appetisers', 'Appetisers'), ('Salads', 'Salads'), ('Starters', 'Starters'), ('Main_Dishes', 'Main_Dishes')], max_length=50),
        ),
    ]
